version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
    environment:
      MONGODB: "mongodb://mongo:27017"
      # NEXT_PUBLIC_API_URL: "localhost"
      # NEXT_PUBLIC_WS_HOST: "localhost"
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
