version: '3.8'

services:

  traefik:
    image: traefik:v2.10
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-certificates:/certificates
    networks:
      - app-network
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # HTTP to HTTPS redirect
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      # Let's Encrypt
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=spam-guessr-certs@sad.bz"
      - "--certificatesresolvers.myresolver.acme.storage=/certificates/acme.json"

  app:
    build:
      context: .
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
    environment:
      MONGODB: "mongodb://mongo:27017"
      # PORT=3000
      # API_PORT=3001
      # WS_PORT=3002
      # NOTE: Have to be set at build time:
      # NEXT_PUBLIC_API_URL: "api.gasser.xyz"
      # NEXT_PUBLIC_WS_HOST: "ws.gasser.xyz"
    depends_on:
      - mongo
    networks:
      - app-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"

      # CORS
      - "traefik.http.middlewares.cors-permissive.headers.accessControlAllowOriginList=*"
      - "traefik.http.middlewares.cors-permissive.headers.accessControlAllowMethods=GET,POST,PUT,DELETE,OPTIONS"
      - "traefik.http.middlewares.cors-permissive.headers.accessControlAllowHeaders=Content-Type,Authorization,X-Requested-With" # Add any others you need, or use "*"
      - "traefik.http.middlewares.cors-permissive.headers.addVaryHeader=true"

      - "traefik.http.routers.app1.rule=Host(`guessr.gasser.xyz`)"
      - "traefik.http.routers.app1.entrypoints=websecure"
      - "traefik.http.routers.app1.tls.certresolver=myresolver"
      - "traefik.http.routers.app1.service=service1"
      - "traefik.http.services.service1.loadbalancer.server.port=3000"

      - "traefik.http.routers.app2.rule=Host(`api.gasser.xyz`)"
      - "traefik.http.routers.app2.entrypoints=websecure"
      - "traefik.http.routers.app2.tls.certresolver=myresolver"
      - "traefik.http.routers.app2.service=service2"
      - "traefik.http.routers.app2.middlewares=cors-permissive"
      - "traefik.http.services.service2.loadbalancer.server.port=3001"

      - "traefik.http.routers.app3.rule=Host(`ws.gasser.xyz`)"
      - "traefik.http.routers.app3.entrypoints=websecure"
      - "traefik.http.routers.app3.tls.certresolver=myresolver"
      - "traefik.http.routers.app3.service=service3"
      - "traefik.http.services.service3.loadbalancer.server.port=3002"
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mongo-data:
  traefik-certificates:

networks:
  app-network:
